// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: {
        message?: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: {
        status?: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type StartBotApiBotStartPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bot/start';
};

export type StartBotApiBotStartPostResponses = {
    /**
     * Successful Response
     */
    200: {
        message?: string;
    };
};

export type StartBotApiBotStartPostResponse = StartBotApiBotStartPostResponses[keyof StartBotApiBotStartPostResponses];
